knpu_oauth2_client:
    clients:
        idp:
            type: generic
            provider_class: Commish\IdpBundle\OAuth\IdpProvider
            provider_options:
                domain: '%env(IDP_BASE_URL)%'
            client_id: '%env(IDP_CLIENT_ID)%'
            client_secret: '%env(IDP_CLIENT_SECRET)%'
            redirect_route: commish_idp_oauth_callback
