security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: idpUuid

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - Commish\IdpBundle\Security\OidcAuthenticator
            entry_point: Commish\IdpBundle\Security\OidcAuthenticator
            logout:
                path: commish_idp_logout

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/oauth, roles: PUBLIC_ACCESS }
        - { path: ^/webhook, roles: PUBLIC_ACCESS }
        - { path: ^/access-denied, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
